server:
  port: 8001
eureka:
  instance:
    hostname: eureka8001.com  # eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    enable-self-preservation: true #测试时关闭自我保护机制，保证不可用服务及时踢出 ,最好是开启的
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka8000.com:8000/eureka/
