server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    #配置阿里数据源 以及数据源相关配置
    type: com.alibaba.druid.pool.DruidDataSource
#    schema: #数据库加载SQL文件的模板
#      - classpath:department.sql
#      - classpath:employee.sql
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#使用spring Data JPA操作关系型数据库
  jpa:
    hibernate:
 #     更新或者创建数据表结构
      ddl-auto: update
 #    控制台显示SQL
    show-sql: true
  redis:
    host: 127.0.0.1
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #mappers.xml扫描加载路径
  config-location: classpath:mybatis/mybatis-config.xml # mybatis 主配置文件
#  configuration:
#    map-underscore-to-camel-case: true   #开启驼峰命名
#debug: true